swagger: "2.0"
info:
  title: "(Go) Scheduler Docs."
  version: "1.0.0"
  description: "This is a documentation about `Scheduler` service."
tags:
  - name: "jobs"
paths:
  /jobs:
    get:
      tags:
        - "jobs"
      summary: "Get current running jobs."
      produces:
        - "application/json"
      responses:
        "200":
          description: "Successful operation"
    post:
      tags:
        - "jobs"
      summary: "Add a new cron job."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Job payload."
          required: true
          schema:
            $ref: "#/definitions/JobPayload"
      responses:
        "200":
          description: "Successful operation"
  /jobs/{job_id}:
    get:
      tags:
        - "jobs"
      summary: "Get specific job."
      produces:
        - "application/json"
      parameters:
        - name: "job_id"
          in: "path"
          description: "Retrieved from `/jobs`"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful operation"
    delete:
      tags:
        - "jobs"
      summary: "Delete specific job."
      produces:
        - "text/plain"
      parameters:
        - name: "job_id"
          in: "path"
          description: "Retrieved from `/jobs`"
          required: true
          type: "integer"
          format: "int64"
      responses:
        "200":
          description: "Successful operation"
definitions:
  JobPayload:
    type: "object"
    properties:
      name:
        type: "string"
      schedule:
        type: "string"
      action:
        type: "string"
      live:
        type: "string"
        enum: ["once", "forever"]
